### ISSUE TITLE
UTF-Decode error

### ISSUE THREAD

**Issue by bashinho** [dievus/msdorkdump#2]
Hi, i did this search 

python3 msdorkdump.py -t github.com -n 1 -d

And this is the result:

[doc extension found] - https://github.com/qreal/qreal/wiki/simonova.doc

Metadata results for simonova.doc
--------------------------------------------------
Traceback (most recent call last):
  File "msdorkdump.py", line 239, in <module>
    msdorker()
  File "msdorkdump.py", line 204, in msdorker
    response = getoutput(cmd)
  File "/usr/lib/python3.8/subprocess.py", line 635, in getoutput
    return getstatusoutput(cmd)[1]
  File "/usr/lib/python3.8/subprocess.py", line 616, in getstatusoutput
    data = check_output(cmd, shell=True, text=True, stderr=STDOUT)
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 495, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.8/subprocess.py", line 1015, in communicate
    stdout = self.stdout.read()
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 326: invalid continuation byte

**Comment by dievus** [comment]
Added an exception for UnicodeDecodeError. Thank you for reporting.
